apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml
images:
- name: 264144530906.dkr.ecr.us-east-1.amazonaws.com/service-2
  newTag: 2e2e27148904c63118b262c567296a35b28c9b5e
- name: service2
  newName: service2
  newTag: latest
