apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml
images:
- name: 264144530906.dkr.ecr.us-east-1.amazonaws.com/service-2
  newTag: 81d98a27c529ecaa6dd2d718d11058dcb718939f
- name: service2
  newName: service2
  newTag: latest
